### PR TITLE
Changes done By Chalom & Awade in Awade's fork

### PR DESCRIPTION
**Pull request by piklprado**
To update our master with the work done by @andrechalom and @awade2 for @awade2 's PhD

### CODE REVIEW

**Comment by piklprado** [comment]
@andrechalom , can you check if is it ok? Thanks!

**Comment by andrechalom** [comment]
Actually, I don't think we should merge this fork back to master without
extensive rework. I think @awade2's modifications make a lot of sense for
speeding up the simulations, but they also break away from much of the
theoretical discussion on object orientation and IBM formalism. We should
probably discuss this more thoroughly in a meeting.

**Comment by piklprado** [comment]
Sure. But even the changes in neighbor distance calculations breaks the
formalism? If not I we could merge this part, because it made the code much
faster.
Em 14/08/2015 12:37, "andrechalom" <notifications@github.com> escreveu:

> Actually, I don't think we should merge this fork back to master without
> extensive rework. I think @awade2's modifications make a lot of sense for
> speeding up the simulations, but they also break away from much of the
> theoretical discussion on object orientation and IBM formalism. We should
> probably discuss this more thoroughly in a meeting.
>
> On Fri, Aug 14, 2015 at 11:31 AM, Paulo Inácio Prado <

**Comment by andrechalom** [comment]
We can do partial merges, of course, but that needs to be developed in a
new branch for "cherry-picking" the changes we want to merge and
extensively testing. The changes were very delicate and required a lot of
error checking before becoming operational.

**Comment by awade2** [comment]
I just want to understand what exactly is "they also break away from much of the discussion on object orientation and IBM formalism." Where is the formalism break? Where is the break on object orientation? My main question is: given that there is a lot of problems on the code and "extensive work" is recquired, what I am doing here? I mean, I am using this "bad" code for a long time, thinking that it was (minimally) good. All my work is based on that. So, what is the sense on runing TWoLife in my PhD, if this code is not respecting the previously discussed (but very confusing and unclear) rules of formalism?

Now, I am very confused and surprised...

**Comment by piklprado** [comment]
@awade2 I sent a private message for you and @andrechalom with my thoughts, but I would like to stress that I see the master branch of TWoLife as an exercise of adherence to OO and ABM formalisms. In this sense, the construnction itself -including these discussions- are much more important than the final solution we find for this branch. So, our personal branches can be seen as more pragmatic solutions given a deadline to solve a specific problem, that take advantage of the code in master branch and also of the discussions. So, I do not think that your branch is "bad code", but I see a difference in being a good code to solve your research questions and if/how should this solutions be merged in the master, as the two branches have very different goals.

**Pull request closed without merging**
